version: '3'
services:
  composition-api:
    image: composition-api-image
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: composition
    restart: always
  nginx:
    image: nginx-image
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nginx
    restart: always
    ports:
      - 8008:80
      - 8009:443
    depends_on:
      - composition-api