version: '3'
services:
  docsim:
    image: semantris-api-image
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: semantris-api
    restart: always
  nginx:
    image: nginx-image
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nginx
    restart: always
    ports:
      - 8002:80
      - 443:443
    depends_on:
      - semantris-api