FROM python:3.9-slim-buster

LABEL maintainer "Kyrylo Malakhov <malakhovks@nas.gov.ua>"
LABEL description "Semantris – Word association game powered by semantic search (with word embeddings)."

COPY ./server /semantris/server
WORKDIR /semantris/server

# Expose the port uWSGI will listen on
EXPOSE 5000

RUN apt-get -y clean \
    && apt-get -y update \
    && apt-get -y install python-dev \
    && apt-get -y install build-essential \
    && apt-get -y install unzip \
    && apt-get -y install bzip2 \
    && apt-get -y install wget \
    && apt-get -y install curl \
    && pip install -r ./deploy/requirements.txt --src /usr/local/src \
    # Download fiction model as a default
    && wget -O ./models/ubercorpus.lowercased.lemmatized.word2vec.300d.bz2 https://lang.org.ua/static/downloads/models/ubercorpus.lowercased.lemmatized.word2vec.300d.bz2 \
    && bzip2 -d ./models/ubercorpus.lowercased.lemmatized.word2vec.300d.bz2 ./models/ubercorpus.lowercased.lemmatized.word2vec.c.text.format.300d \
    && rm -r /root/.cache \
    && apt-get -y clean \
    && apt-get -y autoremove

# Finally, we run uWSGI with the ini file we
# created earlier
CMD ["uwsgi", "--ini", "./deploy/uwsgi.ini"]